# SPDX-FileCopyrightText: 2023 Sidings Media <contact@sidingsmedia.com>
# SPDX-FileCopyrightText: 2020 Chip Zoller and Dan Weru
# SPDX-License-Identifier: MIT

[en]
  title = "Blog | Sidings Media"
  LanguageName = "English"
  weight = 1
